# Generated by Django 4.1.7 on 2023-02-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "congregate",
            "0003_congregateuser_remove_user_avatar_alter_group_admin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
