# Generated by Django 4.1.7 on 2023-02-23 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0004_alter_event_start_time_alter_event_vote_closing_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventOption",
            new_name="Activity",
        ),
    ]
