# Generated by Django 4.1.7 on 2023-02-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0005_rename_eventoption_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
