# Generated by Django 4.1.7 on 2023-02-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0007_remove_event_start_time_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="congregate.congregateuser",
            ),
        ),
    ]
