# Generated by Django 4.1.7 on 2023-02-26 00:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0009_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="decided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="voter",
            field=models.ManyToManyField(
                blank=True, related_name="voted_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 27, 0, 45, 41, 203306, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
