# Generated by Django 4.1.7 on 2023-02-26 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0010_event_decided_event_voter_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 27, 1, 43, 43, 705005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="voter",
            field=models.ManyToManyField(
                blank=True, related_name="voted_events", to="congregate.congregateuser"
            ),
        ),
    ]
