# Generated by Django 4.1.7 on 2023-02-26 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0011_alter_event_vote_closing_time_alter_event_voter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="voter",
            new_name="event_voter",
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 27, 3, 50, 44, 31413, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
