# Generated by Django 4.1.7 on 2023-02-27 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0013_event_decide_event_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="location",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 3, 5, 31, 659002, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
