# Generated by Django 4.1.7 on 2023-02-28 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0014_activity_location_alter_event_vote_closing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 16, 21, 31, 924263, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
