# Generated by Django 4.1.7 on 2023-02-28 18:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0016_alter_activity_creator_alter_event_event_voter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CongregateUser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="activity",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="attending_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatarURL",
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 1, 18, 55, 4, 474844, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
