# Generated by Django 4.1.7 on 2023-03-01 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "congregate",
            "0018_alter_activity_creator_alter_event_vote_closing_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 2, 18, 23, 9, 622526, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
