# Generated by Django 4.1.7 on 2023-03-03 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0020_alter_event_vote_closing_time_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 4, 21, 8, 36, 426414, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
