# Generated by Django 4.1.7 on 2023-03-05 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0022_upload_created_alter_event_vote_closing_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 6, 22, 42, 40, 19393, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="congregate.activity",
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="congregate.group",
            ),
        ),
    ]
