# Generated by Django 4.1.7 on 2023-03-06 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0023_rename_user_upload_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 7, 2, 3, 51, 773593, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
