# Generated by Django 4.1.7 on 2023-03-06 15:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregate", "0024_upload_description_alter_event_vote_closing_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="attendees",
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="attending_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="vote_closing_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 7, 15, 35, 40, 179895, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
